/*******************************************************************
 *Description: Copyright(c) 2018-2025 LiHeBio,All rights reserved.
 *Author: DengXiaoJun
 *Date: 2020-02-11 13:54:56
 *LastEditors: DengXiaoJun
 *LastEditTime: 2020-12-17 09:53:44
 *FilePath: \H360_ActionBoard_ID_2\TaskMain\AppSupport\AppUtil\AppParamIndex.h
 *ModifyRecord1:    
 *ModifyRecord2:    
 *ModifyRecord3:    
 *ModifyRecord4:    
 *ModifyRecord5:    
******************************************************************/
#ifndef __APP_PARAM_INDEX_H_
#define __APP_PARAM_INDEX_H_
#include "stm32f4xx.h"


//磁珠针参数子序号,序号从1开始
typedef enum APP_PARAM_SUB_INDEX_NEEDLE_BEAD
{
    APP_PARAM_SUB_INDEX_NEEDLE_BEAD_ROTATE_RESET_CORRECT					    = 0X01,//磁珠针旋转零位修正
    APP_PARAM_SUB_INDEX_NEEDLE_BEAD_UPDOWN_RESET_CORRECT					    = 0X02,//磁珠针升降零位修正
    APP_PARAM_SUB_INDEX_NEEDLE_BEAD_POS_ROTATE_TO_CLEAN						    = 0X03,//磁珠针旋转到清洗位坐标
    APP_PARAM_SUB_INDEX_NEEDLE_BEAD_POS_UPDOWN_CLEAN						    = 0X04,//磁珠针升降到清洗位坐标
    // APP_PARAM_SUB_INDEX_NEEDLE_BEAD_TIME_MS_CLEAN_SET1						    = 0X05,//磁珠针清洗时间1,毫秒
    // APP_PARAM_SUB_INDEX_NEEDLE_BEAD_TIME_MS_CLEAN_SET2						    = 0X06,//磁珠针清洗时间2,毫秒
    // APP_PARAM_SUB_INDEX_NEEDLE_BEAD_TIME_MS_CLEAN_SET3						    = 0X07,//磁珠针清洗时间3,毫秒
    // APP_PARAM_SUB_INDEX_NEEDLE_BEAD_TIME_MS_CLEAN_SET4						    = 0X08,//磁珠针清洗时间4,毫秒
    // APP_PARAM_SUB_INDEX_NEEDLE_BEAD_TIME_MS_CLEAN_SET5						    = 0X09,//磁珠针清洗时间5,毫秒
    // APP_PARAM_SUB_INDEX_NEEDLE_BEAD_TIME_MS_PRIME							    = 0X0A,//磁珠针清洗液灌注时间,毫秒
    APP_PARAM_SUB_INDEX_NEEDLE_BEAD_POS_ROTATE_TO_R1						    = 0X0B,//磁珠针旋转到R1坐标
    //APP_PARAM_SUB_INDEX_NEEDLE_BEAD_POS_UPDOWN_R1_LIQUID_DETECT_START		    = 0X0C,//磁珠针升降R1吸样探液起始点
    APP_PARAM_SUB_INDEX_NEEDLE_BEAD_POS_UPDOWN_R1_LIQUID_DETECT_MAX_LIMIT	    = 0X0D,//磁珠针升降R1吸样探液极限点
    APP_PARAM_SUB_INDEX_NEEDLE_BEAD_POS_ROTATE_TO_R2						    = 0X0E,//磁珠针旋转到R2坐标
    //APP_PARAM_SUB_INDEX_NEEDLE_BEAD_POS_UPDOWN_R2_LIQUID_DETECT_START		    = 0X0F,//磁珠针升降R2吸样探液起始点
    APP_PARAM_SUB_INDEX_NEEDLE_BEAD_POS_UPDOWN_R2_LIQUID_DETECT_MAX_LIMIT	    = 0X10,//磁珠针升降R2吸样探液极限点
    APP_PARAM_SUB_INDEX_NEEDLE_BEAD_POS_ROTATE_TO_BEAD						    = 0X11,//磁珠针旋转到磁珠位坐标
    //APP_PARAM_SUB_INDEX_NEEDLE_BEAD_POS_UPDOWN_BEAD_LIQUID_DETECT_START		    = 0X12,//磁珠针升降磁珠位吸样探液起始点
    APP_PARAM_SUB_INDEX_NEEDLE_BEAD_POS_UPDOWN_BEAD_LIQUID_DETECT_MAX_LIMIT	    = 0X13,//磁珠针升降磁珠位吸样探液极限点
    APP_PARAM_SUB_INDEX_NEEDLE_BEAD_POS_ROTATE_TO_PLATE_REACTION			    = 0X14,//磁珠针旋转到反应盘排样坐标
    APP_PARAM_SUB_INDEX_NEEDLE_BEAD_POS_UPDOWN_INJECT_AT_BOTTOM			        = 0X15,//磁珠针升降反应盘排样杯底高度
    APP_PARAM_SUB_INDEX_NEEDLE_BEAD_POS_UPDOWN_INJECT_CORRECT				    = 0X16,//磁珠针升降反应盘排样修正高度
    // APP_PARAM_SUB_INDEX_NEEDLE_BEAD_POS_UPDOWN_INJECT3						    = 0X17,//磁珠针升降反应盘排样高度3
    // APP_PARAM_SUB_INDEX_NEEDLE_BEAD_POS_UPDOWN_INJECT4						    = 0X18,//磁珠针升降反应盘排样高度4
    // APP_PARAM_SUB_INDEX_NEEDLE_BEAD_POS_UPDOWN_INJECT5						    = 0X19,//磁珠针升降反应盘排样高度5
    // APP_PARAM_SUB_INDEX_NEEDLE_BEAD_POS_UPDOWN_INJECT6						    = 0X1A,//磁珠针升降反应盘排样高度6
    // APP_PARAM_SUB_INDEX_NEEDLE_BEAD_POS_UPDOWN_INJECT7						    = 0X1B,//磁珠针升降反应盘排样高度7
    // APP_PARAM_SUB_INDEX_NEEDLE_BEAD_POS_UPDOWN_INJECT8_DEEPEST				    = 0X1C,//磁珠针升降反应盘排样高度8,最深
    APP_PARAM_SUB_INDEX_NEEDLE_BEAD_UL_ABSORB_AIR_AFTER_CLEAN				    = 0X1D,//磁珠针清洗完吸空气量
    APP_PARAM_SUB_INDEX_NEEDLE_BEAD_UL_ABSORB_AIR_AFTER_LIQUID_ABSORB		    = 0X1E,//磁珠针吸样完吸空气量
    APP_PARAM_SUB_INDEX_NEEDLE_BEAD_UL_RESERVE_AIR_AFTER_INJECT				    = 0X1F,//磁珠针注液保留空气量
    APP_PARAM_SUB_INDEX_NEEDLE_BEAD_LIQUID_DETECT_REAL_TIME_COMM			    = 0X20,//磁珠针探液通讯使能
    APP_PARAM_SUB_INDEX_NEEDLE_BEAD_PUMP_GEAR_GAP			                    = 0X21,//磁珠针齿间差
    APP_PARAM_SUB_INDEX_NEEDLE_BEAD_UPDOWN_LITTLE_BEAD_MIX			            = 0X22,//磁珠针小磁珠吸吐混匀高度
    APP_PARAM_SUB_INDEX_NEEDLE_BEAD_LIQUID_BOARD_VERSION_WB			            = 0X23,//磁珠针探液板版本号回填确认
}APP_PARAM_SUB_INDEX_NEEDLE_BEAD;

//试剂盘参数子序号,序号从1开始
typedef enum APP_PARAM_SUB_INDEX_PLATE_REAGENT
{
    APP_PARAM_SUB_INDEX_PLATE_REAGENT_ROTATE_RESET_CORRECT		        = 0X01,//试剂盘零位修正
    APP_PARAM_SUB_INDEX_PLATE_REAGENT_CONTROL_VERSION		            = 0X02,//试剂盘控制版本
    APP_PARAM_SUB_INDEX_PLATE_REAGENT_OFFSET_NEEDLE_REAGENT_WITH_R1     = 0X03,//试剂盘相对试剂针到R1偏移
    APP_PARAM_SUB_INDEX_PLATE_REAGENT_OFFSET_NEEDLE_REAGENT_WITH_R2     = 0X04,//试剂盘相对试剂针到R2偏移
    APP_PARAM_SUB_INDEX_PLATE_REAGENT_OFFSET_NEEDLE_BEAD_WITH_R1	    = 0X05,//试剂盘相对磁珠针到R1偏移
    APP_PARAM_SUB_INDEX_PLATE_REAGENT_OFFSET_NEEDLE_BEAD_WITH_R2	    = 0X06,//试剂盘相对磁珠针到R2偏移
    APP_PARAM_SUB_INDEX_PLATE_REAGENT_OFFSET_NEEDLE_BEAD_WITH_BEAD      = 0X07,//试剂盘相对磁珠针到磁珠偏移
    APP_PARAM_SUB_INDEX_PLATE_REAGENT_OFFSET_WITH_QR_SCAN			    = 0X08,//试剂盘到扫码位偏移
    APP_PARAM_SUB_INDEX_PLATE_REAGENT_OFFSET_WITH_QR_RFID			    = 0X09,//试剂盘到扫码位偏移RFID
}APP_PARAM_SUB_INDEX_PLATE_REAGENT;

//杯栈管理参数子序号,序号从1开始
typedef enum APP_PARAM_SUB_INDEX_CUP_TRAY_STACK_MANAGE
{
    APP_PARAM_SUB_INDEX_CUP_TRAY_STACK_MANAGE_NEW_CUP_TRAY_STACK_RESET_CORRECT				  = 0X01,//新杯盘升降电机零位修正
    APP_PARAM_SUB_INDEX_CUP_TRAY_STACK_MANAGE_EMPTY_CUP_TRAY_STACK_RESET_CORRECT		      = 0X02,//空杯盘升降电机零位修正
    APP_PARAM_SUB_INDEX_CUP_TRAY_STACK_MANAGE_CLAMP_RESET_CORRECT						      = 0X03,//夹手电机零位修正
    APP_PARAM_SUB_INDEX_CUP_TRAY_STACK_MANAGE_PUSH_RESET_CORRECT						      = 0X04,//推杆电机零位修正
    APP_PARAM_SUB_INDEX_CUP_TRAY_STACK_MANAGE_POS_CLAMP_OPEN							      = 0X05,//夹手打开坐标
    APP_PARAM_SUB_INDEX_CUP_TRAY_STACK_MANAGE_POS_CLAMP_CLOSE							      = 0X06,//夹手关闭坐标
    APP_PARAM_SUB_INDEX_CUP_TRAY_STACK_MANAGE_POS_PUSH_TRAY_TO_TEST							  = 0X07,//推杆推新盘到测试位坐标
    // APP_PARAM_SUB_INDEX_CUP_TRAY_STACK_MANAGE_OFFSET_PUSH_TRAY_TIGHT_SECOND					  = 0X08,//推杆二次推进补充偏移
    APP_PARAM_SUB_INDEX_CUP_TRAY_STACK_MANAGE_OFFSET_TOP_TO_SENSOR_WHEN_NEW_CUP_TRAY_FULL	  = 0X09,//新杯栈满时,顶部到检测位偏移
    APP_PARAM_SUB_INDEX_CUP_TRAY_STACK_MANAGE_OFFSET_TOP_TO_PALTFORM_WHEN_NEW_CUP_TRAY_FULL	  = 0X0A,//新杯栈满时,顶部到平台偏移
    APP_PARAM_SUB_INDEX_CUP_TRAY_STACK_MANAGE_SPACING_LAYER_NEW_CUP_TRAY					  = 0X0B,//新杯栈上升一个杯盘的偏移
    APP_PARAM_SUB_INDEX_CUP_TRAY_STACK_MANAGE_OFFSET_TOP_TO_SENSOR_WHEN_EMPTY_CUP_TRAY_FULL	  = 0X0C,//空杯栈满时,顶部到检测位偏移
    APP_PARAM_SUB_INDEX_CUP_TRAY_STACK_MANAGE_OFFSET_TOP_TO_PALTFORM_WHEN_EMPTY_CUP_TRAY_FULL = 0X0D,//空杯栈满时,顶部到承接平台偏移
    APP_PARAM_SUB_INDEX_CUP_TRAY_STACK_MANAGE_SPACING_LAYER_EMPTY_CUP_TRAY					  = 0X0E,//空杯栈上升一个杯盘的偏移
}APP_PARAM_SUB_INDEX_CUP_TRAY_STACK_MANAGE;

//辅助参数参数子序号,序号从1开始
typedef enum APP_PARAM_SUB_INDEX_OTHER
{
    APP_PARAM_SUB_INDEX_OTHER_UTIL    = 0X01,
}APP_PARAM_SUB_INDEX_OTHER;


#endif
