#ifndef __CAN2_SUB_RAIL_PARAM_H_
#define __CAN2_SUB_RAIL_PARAM_H_
#include "Can2SubRailBase.h"

//轨道参数主序号枚举
typedef enum CAN2_SUB_RAIL_PARAM_MAIN_INDEX
{
    CAN2_SUB_RAIL_PARAM_MAIN_INDEX_PUSH_IN1 = 0,//进样1
    CAN2_SUB_RAIL_PARAM_MAIN_INDEX_PUSH_IN2 = 1,//进样2
    CAN2_SUB_RAIL_PARAM_MAIN_INDEX_PUSH_OUT1 = 2,//出样1
    CAN2_SUB_RAIL_PARAM_MAIN_INDEX_PUSH_OUT2 = 3,//出样2
    CAN2_SUB_RAIL_PARAM_MAIN_INDEX_RAIL_INDEPENDENT = 4,//轨道独立参数
    CAN2_SUB_RAIL_PARAM_MAIN_INDEX_RAIL_MODULE1 = 5,//轨道模块1参数
    CAN2_SUB_RAIL_PARAM_MAIN_INDEX_RAIL_MODULE2 = 6,//轨道模块2参数
    CAN2_SUB_RAIL_PARAM_MAIN_INDEX_RAIL_MODULE3 = 7,//轨道模块3参数
    CAN2_SUB_RAIL_PARAM_MAIN_INDEX_RAIL_MODULE4 = 8,//轨道模块4参数
    CAN2_SUB_RAIL_PARAM_MAIN_INDEX_HAND_INDEPENDENT = 9,//机械手独立参数
    CAN2_SUB_RAIL_PARAM_MAIN_INDEX_HAND_MODULE1 = 10,//机械手模块1参数
    CAN2_SUB_RAIL_PARAM_MAIN_INDEX_HAND_MODULE2 = 11,//机械手模块2参数
    CAN2_SUB_RAIL_PARAM_MAIN_INDEX_HAND_MODULE3 = 12,//机械手模块3参数
    CAN2_SUB_RAIL_PARAM_MAIN_INDEX_HAND_MODULE4 = 13,//机械手模块4参数
    CAN2_SUB_RAIL_PARAM_MAIN_INDEX_UTIL = 14,//轨道辅助参数
}CAN2_SUB_RAIL_PARAM_MAIN_INDEX;

//轨道参数子序号枚举
typedef enum CAN2_SUB_RAIL_PARAM_INDEX_SUB_PUSH_IN
{
    CAN2_SUB_RAIL_PARAM_INDEX_SUB_PUSH_IN_RESET_CORRECTION,//进样复位修正
    CAN2_SUB_RAIL_PARAM_INDEX_SUB_PUSH_IN_MAX_POS,//进样最大步数
    CAN2_SUB_RAIL_PARAM_INDEX_SUB_PUSH_IN_RESERVE,//进样保留参数
}CAN2_SUB_RAIL_PARAM_INDEX_SUB_PUSH_IN;

//轨道出样子序号枚举
typedef enum CAN2_SUB_RAIL_PARAM_INDEX_SUB_PUSH_OUT
{
    CAN2_SUB_RAIL_PARAM_INDEX_SUB_PUSH_OUT_RESET_CORRECTION,//出样修正
    CAN2_SUB_RAIL_PARAM_INDEX_SUB_PUSH_OUT_ONE_RACK_OFFSET,//出样推一个试管架偏移
    CAN2_SUB_RAIL_PARAM_INDEX_SUB_PUSH_OUT_RESERVE,//出样保留参数
}CAN2_SUB_RAIL_PARAM_INDEX_SUB_PUSH_OUT;

//轨道独立参数子序号枚举
typedef enum CAN2_SUB_RAIL_PARAM_INDEX_SUB_RAIL_INDENPENDENT
{
    CAN2_SUB_RAIL_PARAM_INDEX_SUB_RAIL_INDENPENDENT_RESET_CORRECTION,//轨道复位修正
    CAN2_SUB_RAIL_PARAM_INDEX_SUB_RAIL_INDENPENDENT_EMERGENCY_POS,//轨道急诊位置坐标
    CAN2_SUB_RAIL_PARAM_INDEX_SUB_RAIL_INDENPENDENT_PUSH_IN1_POS,//轨道进样1坐标
    CAN2_SUB_RAIL_PARAM_INDEX_SUB_RAIL_INDENPENDENT_PUSH_IN2_POS,//轨道进样2坐标
    CAN2_SUB_RAIL_PARAM_INDEX_SUB_RAIL_INDENPENDENT_RACK_SCAN_POS,//轨道试管架扫码位坐标
    CAN2_SUB_RAIL_PARAM_INDEX_SUB_RAIL_INDENPENDENT_TUBE1_SCAN_POS,//轨道试管1扫码坐标
    CAN2_SUB_RAIL_PARAM_INDEX_SUB_RAIL_INDENPENDENT_TUBE2_SCAN_POS,//轨道试管2扫码坐标
    CAN2_SUB_RAIL_PARAM_INDEX_SUB_RAIL_INDENPENDENT_TUBE3_SCAN_POS,//轨道试管3扫码坐标
    CAN2_SUB_RAIL_PARAM_INDEX_SUB_RAIL_INDENPENDENT_TUBE4_SCAN_POS,//轨道试管4扫码坐标
    CAN2_SUB_RAIL_PARAM_INDEX_SUB_RAIL_INDENPENDENT_TUBE5_SCAN_POS,//轨道试管5扫码坐标
    CAN2_SUB_RAIL_PARAM_INDEX_SUB_RAIL_INDENPENDENT_ROTATE1_POS,//轨道旋转位1坐标
    CAN2_SUB_RAIL_PARAM_INDEX_SUB_RAIL_INDENPENDENT_ROTATE2_POS,//轨道旋转位2坐标
    CAN2_SUB_RAIL_PARAM_INDEX_SUB_RAIL_INDENPENDENT_PUSH_OUT1_POS,//轨道出样1坐标
    CAN2_SUB_RAIL_PARAM_INDEX_SUB_RAIL_INDENPENDENT_PUSH_OUT2_POS,//轨道出样2坐标
    CAN2_SUB_RAIL_PARAM_INDEX_SUB_RAIL_INDENPENDENT_RESERVE,//轨道保留参数
}CAN2_SUB_RAIL_PARAM_INDEX_SUB_RAIL_INDENPENDENT;

//轨道模块参数子序号枚举
typedef enum CAN2_SUB_RAIL_PARAM_INDEX_SUB_RAIL_MODULE
{
    CAN2_SUB_RAIL_PARAM_INDEX_SUB_RAIL_MODULE_WAIT_TEST1_POS,//轨道模块待测缓冲区1坐标
    CAN2_SUB_RAIL_PARAM_INDEX_SUB_RAIL_MODULE_WAIT_TEST2_POS,//轨道模块待测缓冲区2坐标
    CAN2_SUB_RAIL_PARAM_INDEX_SUB_RAIL_MODULE_WAIT_TEST3_POS,//轨道模块待测缓冲区3坐标
    CAN2_SUB_RAIL_PARAM_INDEX_SUB_RAIL_MODULE_RE_TEST1_POS,//轨道模块重测区1坐标
    CAN2_SUB_RAIL_PARAM_INDEX_SUB_RAIL_MODULE_RE_TEST2_POS,//轨道模块重测区2坐标
    CAN2_SUB_RAIL_PARAM_INDEX_SUB_RAIL_MODULE_RE_TEST3_POS,//轨道模块重测区3坐标
    CAN2_SUB_RAIL_PARAM_INDEX_SUB_RAIL_MODULE_RE_TEST4_POS,//轨道模块重测区4坐标
    CAN2_SUB_RAIL_PARAM_INDEX_SUB_RAIL_MODULE_RE_TEST5_POS,//轨道模块重测区5坐标
    CAN2_SUB_RAIL_PARAM_INDEX_SUB_RAIL_MODULE_RE_TEST6_POS,//轨道模块重测区6坐标
    CAN2_SUB_RAIL_PARAM_INDEX_SUB_RAIL_MODULE_RE_TEST7_POS,//轨道模块重测区7坐标
    CAN2_SUB_RAIL_PARAM_INDEX_SUB_RAIL_MODULE_RE_TEST8_POS,//轨道模块重测区8坐标
    CAN2_SUB_RAIL_PARAM_INDEX_SUB_RAIL_MODULE_TESTING_PUT,//轨道模块测试区放架位
    CAN2_SUB_RAIL_PARAM_INDEX_SUB_RAIL_MODULE_TESTING_CATCH,//轨道模块测试区取架位
    CAN2_SUB_RAIL_PARAM_INDEX_SUB_RAIL_MODULE_TESTING_ABSORB,//轨道模块测试区吸样位
    CAN2_SUB_RAIL_PARAM_INDEX_SUB_RAIL_MODULE_RESERVE,
}CAN2_SUB_RAIL_PARAM_INDEX_SUB_RAIL_MODULE;

//轨道机械手独立参数子序号枚举
typedef enum CAN2_SUB_RAIL_PARAM_INDEX_SUB_HAND_INDENPENDENT
{
    CAN2_SUB_RAIL_PARAM_INDEX_SUB_HAND_INDENPENDENT_UPDOWN_RESET_CORRECTION,//机械手升降复位修正
    CAN2_SUB_RAIL_PARAM_INDEX_SUB_HAND_INDENPENDENT_BACKFRONT_RESET_CORRECTION,//机械手前后复位修正
    CAN2_SUB_RAIL_PARAM_INDEX_SUB_HAND_INDENPENDENT_ROTATE_RESET_CORRECTION,//机械手旋转复位修正
    CAN2_SUB_RAIL_PARAM_INDEX_SUB_HAND_INDENPENDENT_UPDOWN_HIGH_MAX_POS,//机械手升降最高位置
    CAN2_SUB_RAIL_PARAM_INDEX_SUB_HAND_INDENPENDENT_UPDOWN_LOW_MIN_POS,//机械手升降最低位置
    CAN2_SUB_RAIL_PARAM_INDEX_SUB_HAND_INDENPENDENT_BACKFRONT_PUSHIN_POS,//机械手前后进样取放架位
    CAN2_SUB_RAIL_PARAM_INDEX_SUB_HAND_INDENPENDENT_BACKFRONT_PUSH_OUT_POS,//机械手前后出样取放架位
    CAN2_SUB_RAIL_PARAM_INDEX_SUB_HAND_INDENPENDENT_BACKFRONT_EMERGENCY_POS,//机械手前后急诊取放架位
    CAN2_SUB_RAIL_PARAM_INDEX_SUB_HAND_INDENPENDENT_BACKFRONT_UTIL_ROTATE_OFFSET,//机械手前后在旋转时候的辅助旋转偏移
    CAN2_SUB_RAIL_PARAM_INDEX_SUB_HAND_INDENPENDENT_ROTATE_DIR_PUSH_IN_POS,//机械手旋转到进样方向坐标
    CAN2_SUB_RAIL_PARAM_INDEX_SUB_HAND_INDENPENDENT_ROTATE_DIR_EMERGENCY_POS,//机械手旋转到急诊方向坐标
    CAN2_SUB_RAIL_PARAM_INDEX_SUB_HAND_INDENPENDENT_RESERVE,
}CAN2_SUB_RAIL_PARAM_INDEX_SUB_HAND_INDENPENDENT;

//轨道机械手模块参数子序号枚举
typedef enum CAN2_SUB_RAIL_PARAM_INDEX_SUB_HAND_MODULE
{
    CAN2_SUB_RAIL_PARAM_INDEX_SUB_HAND_MODULE_BACKFRONT_WAIT_TEST_POS,//机械手前后到待测区和测试区取放位置
    CAN2_SUB_RAIL_PARAM_INDEX_SUB_HAND_MODULE_BACKFRONT_RE_TEST_POS,//机械手前后到重测区取放位置
    CAN2_SUB_RAIL_PARAM_INDEX_SUB_HAND_MODULE_RESERVE,
}CAN2_SUB_RAIL_PARAM_INDEX_SUB_HAND_MODULE;

//辅助参数子序号枚举
typedef enum CAN2_SUB_RAIL_PARAM_INDEX_SUB_UTIL
{
    CAN2_SUB_RAIL_PARAM_INDEX_SUB_HAND_UTIL_RESERVE,
}CAN2_SUB_RAIL_PARAM_INDEX_SUB_UTIL;

//轨道板读取参数
LH_ERR Can2SubRailParamRead(CAN2_SUB_RAIL_PARAM_MAIN_INDEX mainIndex,uint16_t subIndex,int32_t* paramReadPtr);

//轨道板写入参数
LH_ERR Can2SubRailParamWrite(CAN2_SUB_RAIL_PARAM_MAIN_INDEX mainIndex,uint16_t subIndex,int32_t paramWrite);

//初始化成默认参数
LH_ERR Can2SubRailParamResetDeafultParam(void);


#endif



