#include "BoardConfigInc.h"
//配置主板输出IO初始化的电平
#include "BoardInOut.h"

//板上IO初始化的电平状态配置
const BitAction  boardOutInitLevelConfigArray[BOARD_OUT_PIN_COUNT] = {
    Bit_SET,//BOARD_OUT_CPLD_CDC1
    Bit_SET,//BOARD_OUT_CPLD_CDC2
    Bit_SET,//BOARD_OUT_CPLD_CDC3
    Bit_SET,//BOARD_OUT_CPLD_CDC4
    Bit_SET,//BOARD_OUT_CPLD_CDC5
    Bit_SET,//BOARD_OUT_CPLD_CDC6
    Bit_SET,//BOARD_OUT_CPLD_CDC7
    Bit_SET,//BOARD_OUT_CPLD_CDC8
    Bit_SET,//BOARD_OUT_CPLD_CDC9
    Bit_SET,//BOARD_OUT_CPLD_CDC10
    Bit_SET,//BOARD_OUT_CPLD_CDC11
    Bit_SET,//BOARD_OUT_CPLD_CDC12
    Bit_SET,//BOARD_OUT_CPLD_CDC13
    Bit_SET,//BOARD_OUT_CPLD_CDC14
    Bit_SET,//BOARD_OUT_CPLD_CDC15
    Bit_SET,//BOARD_OUT_CPLD_CDC16
    Bit_SET,//BOARD_OUT_CPLD_CDC17
    Bit_SET,//BOARD_OUT_CPLD_CDC18
    Bit_SET,//BOARD_OUT_CPLD_CDC19
    Bit_SET,//BOARD_OUT_CPLD_CDC20
    Bit_SET,//BOARD_OUT_CPLD_CDC21
    Bit_SET,//BOARD_OUT_CPLD_CDC22
    Bit_SET,//BOARD_OUT_CPLD_CDC23
    Bit_SET,//BOARD_OUT_CPLD_CDC24
    Bit_SET,//BOARD_OUT_CPLD_CDC25
    Bit_SET,//BOARD_OUT_CPLD_CDC26
    Bit_SET,//BOARD_OUT_CPLD_CDC27
    Bit_SET,//BOARD_OUT_CPLD_CDC28
    Bit_SET,//BOARD_OUT_CPLD_CDC29
    Bit_SET,//BOARD_OUT_CPLD_CDC30
    Bit_SET,//BOARD_OUT_CPLD_CDC31
    Bit_SET,//BOARD_OUT_CPLD_CDC32
    Bit_SET,//BOARD_OUT_CPLD_CDC33
    Bit_SET,//BOARD_OUT_CPLD_CDC34
    Bit_SET,//BOARD_OUT_CPLD_CDC35
    Bit_SET,//BOARD_OUT_CPLD_CDC36
    Bit_SET,//BOARD_OUT_MCU_SLAVE_SEN17_PC4
    Bit_SET,//BOARD_OUT_MCU_SLAVE_SEN18_PA7
    Bit_SET,//BOARD_OUT_MCU_SLAVE_SEN19_PA6
    Bit_SET,//BOARD_OUT_MCU_SLAVE_SEN20_PA5
    Bit_SET,//BOARD_OUT_MCU_SLAVE_SEN21_PA4
    Bit_SET,//BOARD_OUT_MCU_SLAVE_SEN22_PA3
    Bit_SET,//BOARD_OUT_MCU_SLAVE_SEN23_PF8
    Bit_SET,//BOARD_OUT_MCU_SLAVE_SEN24_PF9
    Bit_SET,//BOARD_OUT_MCU_SLAVE_SEN25_PF10
    Bit_SET,//BOARD_OUT_MCU_SLAVE_SEN26_PH3
    Bit_SET,//BOARD_OUT_MCU_SLAVE_SEN27_PH2
    Bit_SET,//BOARD_OUT_MCU_SLAVE_SEN28_PA2
    Bit_SET,//BOARD_OUT_MCU_SLAVE_DC1_VAVLE_PC8
    Bit_SET,//BOARD_OUT_MCU_SLAVE_DC2_RUBBISH_MOTOR1_PG9
    Bit_SET,//BOARD_OUT_MCU_SLAVE_DC3_RUBBISH_MOTOR2_PD6
    Bit_SET,//BOARD_OUT_MCU_SLAVE_DC4_RUBBISH_MOTOR3_PI3
    Bit_SET,//BOARD_OUT_MCU_SLAVE_DC5_RUBBISH_MOTOR4_PI2
    Bit_SET,//BOARD_OUT_MCU_YM1_ARM3_PB4
    Bit_SET,//BOARD_OUT_MCU_YM1_ARM4_PG15
};


//板上IO初始化的上下拉配置
const GPIOPuPd_TypeDef  boardOutInitPullConfigArray[BOARD_OUT_PIN_COUNT] = {
    GPIO_PuPd_UP,//BOARD_OUT_CPLD_CDC1
    GPIO_PuPd_UP,//BOARD_OUT_CPLD_CDC2
    GPIO_PuPd_UP,//BOARD_OUT_CPLD_CDC3
    GPIO_PuPd_UP,//BOARD_OUT_CPLD_CDC4
    GPIO_PuPd_UP,//BOARD_OUT_CPLD_CDC5
    GPIO_PuPd_UP,//BOARD_OUT_CPLD_CDC6
    GPIO_PuPd_UP,//BOARD_OUT_CPLD_CDC7
    GPIO_PuPd_UP,//BOARD_OUT_CPLD_CDC8
    GPIO_PuPd_UP,//BOARD_OUT_CPLD_CDC9
    GPIO_PuPd_UP,//BOARD_OUT_CPLD_CDC10
    GPIO_PuPd_UP,//BOARD_OUT_CPLD_CDC11
    GPIO_PuPd_UP,//BOARD_OUT_CPLD_CDC12
    GPIO_PuPd_UP,//BOARD_OUT_CPLD_CDC13
    GPIO_PuPd_UP,//BOARD_OUT_CPLD_CDC14
    GPIO_PuPd_UP,//BOARD_OUT_CPLD_CDC15
    GPIO_PuPd_UP,//BOARD_OUT_CPLD_CDC16
    GPIO_PuPd_UP,//BOARD_OUT_CPLD_CDC17
    GPIO_PuPd_UP,//BOARD_OUT_CPLD_CDC18
    GPIO_PuPd_UP,//BOARD_OUT_CPLD_CDC19
    GPIO_PuPd_UP,//BOARD_OUT_CPLD_CDC20
    GPIO_PuPd_UP,//BOARD_OUT_CPLD_CDC21
    GPIO_PuPd_UP,//BOARD_OUT_CPLD_CDC22
    GPIO_PuPd_UP,//BOARD_OUT_CPLD_CDC23
    GPIO_PuPd_UP,//BOARD_OUT_CPLD_CDC24
    GPIO_PuPd_UP,//BOARD_OUT_CPLD_CDC25
    GPIO_PuPd_UP,//BOARD_OUT_CPLD_CDC26
    GPIO_PuPd_UP,//BOARD_OUT_CPLD_CDC27
    GPIO_PuPd_UP,//BOARD_OUT_CPLD_CDC28
    GPIO_PuPd_UP,//BOARD_OUT_CPLD_CDC29
    GPIO_PuPd_UP,//BOARD_OUT_CPLD_CDC30
    GPIO_PuPd_UP,//BOARD_OUT_CPLD_CDC31
    GPIO_PuPd_UP,//BOARD_OUT_CPLD_CDC32
    GPIO_PuPd_UP,//BOARD_OUT_CPLD_CDC33
    GPIO_PuPd_UP,//BOARD_OUT_CPLD_CDC34
    GPIO_PuPd_UP,//BOARD_OUT_CPLD_CDC35
    GPIO_PuPd_UP,//BOARD_OUT_CPLD_CDC36
    GPIO_PuPd_UP,//BOARD_OUT_MCU_SLAVE_SEN17_PC4
    GPIO_PuPd_UP,//BOARD_OUT_MCU_SLAVE_SEN18_PA7
    GPIO_PuPd_UP,//BOARD_OUT_MCU_SLAVE_SEN19_PA6
    GPIO_PuPd_UP,//BOARD_OUT_MCU_SLAVE_SEN20_PA5
    GPIO_PuPd_UP,//BOARD_OUT_MCU_SLAVE_SEN21_PA4
    GPIO_PuPd_UP,//BOARD_OUT_MCU_SLAVE_SEN22_PA3
    GPIO_PuPd_UP,//BOARD_OUT_MCU_SLAVE_SEN23_PF8
    GPIO_PuPd_UP,//BOARD_OUT_MCU_SLAVE_SEN24_PF9
    GPIO_PuPd_UP,//BOARD_OUT_MCU_SLAVE_SEN25_PF10
    GPIO_PuPd_UP,//BOARD_OUT_MCU_SLAVE_SEN26_PH3
    GPIO_PuPd_UP,//BOARD_OUT_MCU_SLAVE_SEN27_PH2
    GPIO_PuPd_UP,//BOARD_OUT_MCU_SLAVE_SEN28_PA2
    GPIO_PuPd_UP,//BOARD_OUT_MCU_SLAVE_DC1_VAVLE_PC8
    GPIO_PuPd_UP,//BOARD_OUT_MCU_SLAVE_DC2_RUBBISH_MOTOR1_PG9
    GPIO_PuPd_UP,//BOARD_OUT_MCU_SLAVE_DC3_RUBBISH_MOTOR2_PD6
    GPIO_PuPd_UP,//BOARD_OUT_MCU_SLAVE_DC4_RUBBISH_MOTOR3_PI3
    GPIO_PuPd_UP,//BOARD_OUT_MCU_SLAVE_DC5_RUBBISH_MOTOR4_PI2
    GPIO_PuPd_UP,//BOARD_OUT_MCU_YM1_ARM3_PB4
    GPIO_PuPd_UP,//BOARD_OUT_MCU_YM1_ARM4_PG15
};























