/*******************************************************************
**Description: Copyright(c) 2018-2025 LiHeBio,All rights reserved.
**Author: DengXiaoJun
**Date: 2020-06-19 09:29:27
**LastEditors: DengXiaoJun
**LastEditTime: 2020-06-19 11:43:39
**ModifyRecord1:    
**ModifyRecord2:    
**ModifyRecord3:    
**ModifyRecord4:    
**ModifyRecord5:    
******************************************************************/
#include "BoardInOutConfig.h"
#include "BoardInOut.h"

//主板输入初始化
//配置输入上拉还是下拉
const MCU_PORT_PULL boardInInitPullConfigArray[BOARD_IN_COUNT] = {
    MCU_PORT_PULL_PULLDOWN,//BOARD_IN_ARM_SEN1_PH10
    MCU_PORT_PULL_PULLDOWN,//BOARD_IN_ARM_SEN2_PH9
    MCU_PORT_PULL_PULLDOWN,//BOARD_IN_ARM_SEN3_PH8
    MCU_PORT_PULL_PULLDOWN,//BOARD_IN_ARM_SEN4_PH7
    MCU_PORT_PULL_PULLDOWN,//BOARD_IN_ARM_SEN5_PH6
    MCU_PORT_PULL_PULLDOWN,//BOARD_IN_ARM_SEN6_PF11
    MCU_PORT_PULL_PULLDOWN,//BOARD_IN_ARM_SEN7_PB1
    MCU_PORT_PULL_PULLDOWN,//BOARD_IN_ARM_SEN8_PB0
    MCU_PORT_PULL_PULLDOWN,//BOARD_IN_ARM_SEN9_PC5
    MCU_PORT_PULL_PULLDOWN,//BOARD_IN_ARM_SEN10_PC4
    MCU_PORT_PULL_PULLDOWN,//BOARD_IN_ARM_SEN11_PH3
    MCU_PORT_PULL_PULLDOWN,//BOARD_IN_ARM_SEN12_PH2
    MCU_PORT_PULL_PULLDOWN,//BOARD_IN_ARM_SEN13_PA1
    MCU_PORT_PULL_PULLDOWN,//BOARD_IN_ARM_SEN14_PA0
    MCU_PORT_PULL_PULLDOWN,//BOARD_IN_ARM_SEN15_PB9
    MCU_PORT_PULL_PULLDOWN,//BOARD_IN_ARM_SEN16_PI4
    MCU_PORT_PULL_PULLDOWN,//BOARD_IN_ARM_SEN17_PI5
    MCU_PORT_PULL_PULLDOWN,//BOARD_IN_ARM_SEN18_PI6
    MCU_PORT_PULL_PULLDOWN,//BOARD_IN_ARM_SEN19_PI7
    MCU_PORT_PULL_PULLDOWN,//BOARD_IN_ARM_SEN20_PF10
    MCU_PORT_PULL_PULLDOWN,//BOARD_IN_ARM_SEN21_PF9
    MCU_PORT_PULL_PULLDOWN,//BOARD_IN_ARM_SEN22_PF8
    MCU_PORT_PULL_PULLDOWN,//BOARD_IN_ARM_SEN23_PF6
    MCU_PORT_PULL_PULLDOWN,//BOARD_IN_ARM_SEN24_PF7
    MCU_PORT_PULL_PULLDOWN,//BOARD_IN_ARM_SEN25_PI11
    MCU_PORT_PULL_PULLDOWN,//BOARD_IN_ARM_SEN26_PI10
    MCU_PORT_PULL_PULLDOWN,//BOARD_IN_ARM_SEN27_PI9
    MCU_PORT_PULL_PULLDOWN,//BOARD_IN_ARM_SEN28_PC13
    MCU_PORT_PULL_PULLDOWN,//BOARD_IN_ARM_SEN29_PI8
    MCU_PORT_PULL_PULLDOWN,//BOARD_IN_ARM_SEN30_PE2
    MCU_PORT_PULL_PULLDOWN,//BOARD_IN_ARM_SEN31_PE3
    MCU_PORT_PULL_PULLDOWN,//BOARD_IN_ARM_SEN32_PE4
};


//板上IO初始化的电平状态配置
const BitAction  boardOutInitLevelConfigArray[BOARD_OUT_COUNT] = {
    Bit_SET,//BOARD_OUT_ARM_OUT1_PG15
    Bit_SET,//BOARD_OUT_ARM_OUT2_PB3
    Bit_SET,//BOARD_OUT_ARM_OUT3_PB4
    Bit_SET,//BOARD_OUT_ARM_OUT4_PG14
    Bit_SET,//BOARD_OUT_ARM_OUT5_PG13
    Bit_SET,//BOARD_OUT_ARM_OUT6_PG11
    Bit_SET,//BOARD_OUT_ARM_OUT7_PI3
    Bit_SET,//BOARD_OUT_ARM_OUT8_PA15
    Bit_SET,//BOARD_OUT_ARM_OUT9_PD6
    Bit_SET,//BOARD_OUT_ARM_OUT10_PG10
    Bit_SET,//BOARD_OUT_ARM_OUT11_PG9
    Bit_SET,//BOARD_OUT_ARM_OUT12_PD7
    Bit_SET,//BOARD_OUT_ARM_OUT13_PG8
    Bit_SET,//BOARD_OUT_ARM_OUT14_PI1
    Bit_SET,//BOARD_OUT_ARM_OUT15_PI0
    Bit_SET,//BOARD_OUT_ARM_OUT16_PG6
    Bit_SET,//BOARD_OUT_ARM_OUT17_PG7
    Bit_SET,//BOARD_OUT_ARM_OUT18_PH12
    Bit_SET,//BOARD_OUT_ARM_OUT19_PI2
    Bit_SET,//BOARD_OUT_ARM_OUT20_PD3
};


//板上IO初始化的上下拉配置
const MCU_PORT_PULL  boardOutInitPullConfigArray[BOARD_OUT_COUNT] = {
    MCU_PORT_PULL_PULLUP,//BOARD_OUT_ARM_OUT1_PG15
    MCU_PORT_PULL_PULLUP,//BOARD_OUT_ARM_OUT2_PB3
    MCU_PORT_PULL_PULLUP,//BOARD_OUT_ARM_OUT3_PB4
    MCU_PORT_PULL_PULLUP,//BOARD_OUT_ARM_OUT4_PG14
    MCU_PORT_PULL_PULLUP,//BOARD_OUT_ARM_OUT5_PG13
    MCU_PORT_PULL_PULLUP,//BOARD_OUT_ARM_OUT6_PG11
    MCU_PORT_PULL_PULLUP,//BOARD_OUT_ARM_OUT7_PI3
    MCU_PORT_PULL_PULLUP,//BOARD_OUT_ARM_OUT8_PA15
    MCU_PORT_PULL_PULLUP,//BOARD_OUT_ARM_OUT9_PD6
    MCU_PORT_PULL_PULLUP,//BOARD_OUT_ARM_OUT10_PG10
    MCU_PORT_PULL_PULLUP,//BOARD_OUT_ARM_OUT11_PG9
    MCU_PORT_PULL_PULLUP,//BOARD_OUT_ARM_OUT12_PD7
    MCU_PORT_PULL_PULLUP,//BOARD_OUT_ARM_OUT13_PG8
    MCU_PORT_PULL_PULLUP,//BOARD_OUT_ARM_OUT14_PI1
    MCU_PORT_PULL_PULLUP,//BOARD_OUT_ARM_OUT15_PI0
    MCU_PORT_PULL_PULLUP,//BOARD_OUT_ARM_OUT16_PG6
    MCU_PORT_PULL_PULLUP,//BOARD_OUT_ARM_OUT17_PG7
    MCU_PORT_PULL_PULLUP,//BOARD_OUT_ARM_OUT18_PH12
    MCU_PORT_PULL_PULLUP,//BOARD_OUT_ARM_OUT19_PI2
    MCU_PORT_PULL_PULLUP,//BOARD_OUT_ARM_OUT20_PD3
};
