/*******************************************************************
 *Description: Copyright(c) 2018-2025 LiHeBio,All rights reserved.
 *Author: DengXiaoJun
 *Date: 2020-03-02 10:46:11
 *LastEditors: DengXiaoJun
 *LastEditTime: 2020-03-17 18:01:20
 *FilePath: \Code\CommonFunc\Can2SubBoardTC\Can2SubBoardTcParam.h
 *ModifyRecord1:    
 *ModifyRecord2:    
 *ModifyRecord3:    
 *ModifyRecord4:    
 *ModifyRecord5:    
******************************************************************/
#ifndef __CAN2_SUB_BOARD_TC_PARAM_H_
#define __CAN2_SUB_BOARD_TC_PARAM_H_
#include "Can2ProcMain.h"
#include "Can2SubCommBaseInc.h"


//参数读写主序号
typedef enum CAN2_SUB_BOARD_TC_PARAM_MAIN
{
    CAN2_SUB_BOARD_TC_PARAM_MAIN_BOARD_TEMP      = 0x00,//板上
    CAN2_SUB_BOARD_TC_PARAM_MAIN_ENVIR           = 0x01,//环境
    CAN2_SUB_BOARD_TC_PARAM_MAIN_PLATE_REACTION  = 0x02,//反应盘
    CAN2_SUB_BOARD_TC_PARAM_MAIN_PLATE_WASH      = 0x03,//清洗盘
    CAN2_SUB_BOARD_TC_PARAM_MAIN_PLATE_REAGENT   = 0x04,//试剂盘
}CAN2_SUB_BOARD_TC_PARAM_MAIN;

//参数读写子序号,板上
typedef enum CAN2_SUB_BOARD_TC_PARAM_SUB_BOARD_TEMP
{
    CAN2_SUB_BOARD_TC_PARAM_SUB_BOARD_TEMP_MAX_LIMIT = 0X00,//保护温度上
    CAN2_SUB_BOARD_TC_PARAM_SUB_BOARD_TEMP_MIN_LIMIT = 0X01,//保护温度下
}CAN2_SUB_BOARD_TC_PARAM_SUB_BOARD_TEMP;

//参数读写子序号,环境
typedef enum CAN2_SUB_BOARD_TC_PARAM_SUB_ENVIR
{
    CAN2_SUB_BOARD_TC_PARAM_SUB_ENVIR_MAX_LIMIT = 0X00,//保护温度上
    CAN2_SUB_BOARD_TC_PARAM_SUB_ENVIR_MIN_LIMIT = 0X01,//保护温度下
    CAN2_SUB_BOARD_TC_PARAM_SUB_ENVIR_TEMP_OPEN_FAN = 0X02,//风扇打开温度
}CAN2_SUB_BOARD_TC_PARAM_SUB_ENVIR;

//参数读写子序号,反应盘
typedef enum CAN2_SUB_BOARD_TC_PARAM_SUB_PLATE_REACTION
{
    CAN2_SUB_BOARD_TC_PARAM_SUB_PLATE_REACTION_TARGET_TEMP       = 0X00,//目标温度
    CAN2_SUB_BOARD_TC_PARAM_SUB_PLATE_REACTION_KP                = 0X01,//比例系数
    CAN2_SUB_BOARD_TC_PARAM_SUB_PLATE_REACTION_KI                = 0X02,//积分系数
    CAN2_SUB_BOARD_TC_PARAM_SUB_PLATE_REACTION_KD                = 0X03,//微分系数
    CAN2_SUB_BOARD_TC_PARAM_SUB_PLATE_REACTION_HIGH_THRESHOLD    = 0X04,//全速降温上阈值
    CAN2_SUB_BOARD_TC_PARAM_SUB_PLATE_REACTION_LOW_THRESHOLD     = 0X05,//全速升温下阈值
    CAN2_SUB_BOARD_TC_PARAM_SUB_PLATE_REACTION_MAX_POWER         = 0X06,//最大输出功率
    CAN2_SUB_BOARD_TC_PARAM_SUB_PLATE_REACTION_MIN_POWER         = 0X07,//最小输出功率
    CAN2_SUB_BOARD_TC_PARAM_SUB_PLATE_REACTION_HIGH_PROTECT      = 0X08,//保护温度上
    CAN2_SUB_BOARD_TC_PARAM_SUB_PLATE_REACTION_LOW_PROTECT       = 0X09,//保护温度下
    CAN2_SUB_BOARD_TC_PARAM_SUB_PLATE_REACTION_KI_TIME_SECOND    = 0X0A,//积分时间,秒
    CAN2_SUB_BOARD_TC_PARAM_SUB_PLATE_REACTION_KD_TIME_SECOND    = 0X0B,//微分时间,秒
}CAN2_SUB_BOARD_TC_PARAM_SUB_PLATE_REACTION;

//参数读写子序号,清洗盘
typedef enum CAN2_SUB_BOARD_TC_PARAM_SUB_PLATE_WASH
{
    CAN2_SUB_BOARD_TC_PARAM_SUB_PLATE_WASH_TARGET_TEMP     = 0X00,//目标温度
    CAN2_SUB_BOARD_TC_PARAM_SUB_PLATE_WASH_KP              = 0X01,//比例系数
    CAN2_SUB_BOARD_TC_PARAM_SUB_PLATE_WASH_KI              = 0X02,//积分系数
    CAN2_SUB_BOARD_TC_PARAM_SUB_PLATE_WASH_KD              = 0X03,//微分系数
    CAN2_SUB_BOARD_TC_PARAM_SUB_PLATE_WASH_HIGH_THRESHOLD  = 0X04,//全速降温上阈值
    CAN2_SUB_BOARD_TC_PARAM_SUB_PLATE_WASH_LOW_THRESHOLD   = 0X05,//全速升温下阈值
    CAN2_SUB_BOARD_TC_PARAM_SUB_PLATE_WASH_MAX_POWER       = 0X06,//最大输出功率
    CAN2_SUB_BOARD_TC_PARAM_SUB_PLATE_WASH_MIN_POWER       = 0X07,//最小输出功率
    CAN2_SUB_BOARD_TC_PARAM_SUB_PLATE_WASH_HIGH_PROTECT    = 0X08,//保护温度上
    CAN2_SUB_BOARD_TC_PARAM_SUB_PLATE_WASH_LOW_PROTECT     = 0X09,//保护温度下
    CAN2_SUB_BOARD_TC_PARAM_SUB_PLATE_WASH_KI_TIME_SECOND  = 0X0A,//积分时间,秒
    CAN2_SUB_BOARD_TC_PARAM_SUB_PLATE_WASH_KD_TIME_SECOND  = 0X0B,//微分时间,秒
}CAN2_SUB_BOARD_TC_PARAM_SUB_PLATE_WASH;

//参数读写子序号,试剂盘
typedef enum CAN2_SUB_BOARD_TC_PARAM_SUB_PLATE_REAGENT
{
    CAN2_SUB_BOARD_TC_PARAM_SUB_PLATE_REAGENT_TARGET_TEMP    = 0X00,//目标温度
    CAN2_SUB_BOARD_TC_PARAM_SUB_PLATE_REAGENT_MAX_POWER      = 0X01,//最大输出功率
    CAN2_SUB_BOARD_TC_PARAM_SUB_PLATE_REAGENT_MIN_POWER      = 0X02,//最小输出功率
    CAN2_SUB_BOARD_TC_PARAM_SUB_PLATE_REAGENT_HIGH_PROTECT   = 0X03,//保护温度上
    CAN2_SUB_BOARD_TC_PARAM_SUB_PLATE_REAGENT_LOW_PROTECT    = 0X04,//保护温度下
    CAN2_SUB_BOARD_TC_PARAM_SUB_PLATE_REAGENT_COOLER_DEVICE  = 0X05,//试剂盘制冷装置
}CAN2_SUB_BOARD_TC_PARAM_SUB_PLATE_REAGENT;

//温控读取参数
LH_ERR Can2SubBoardTcParamRead(CAN2_SUB_BOARD_TC_PARAM_MAIN mainIndex,uint8_t subIndex,float* paramResult);

//温控写入参数
LH_ERR Can2SubBoardTcParamWrite(CAN2_SUB_BOARD_TC_PARAM_MAIN mainIndex,uint8_t subIndex,float paramWrite);


#endif



