/*******************************************************************
 *Description: Copyright(c) 2018-2025 LiHeBio,All rights reserved.
 *Author: DengXiaoJun
 *Date: 2020-05-03 13:56:10
 *LastEditors: DengXiaoJun
 *LastEditTime: 2020-05-03 13:57:33
 *FilePath: \LH_TC_APP_V2.3\TaskMain\ServiceSupport\ServiceUtil\ServiceUtilParamIndex.h
 *ModifyRecord1:    
 *ModifyRecord2:    
 *ModifyRecord3:    
 *ModifyRecord4:    
 *ModifyRecord5:    
******************************************************************/
#ifndef  __SERVICE_UTIL_PARAM_INDEX_H_
#define  __SERVICE_UTIL_PARAM_INDEX_H_


//参数读写主序号
typedef enum SERVICE_PARAM_PARAM_MAIN
{
    SERVICE_PARAM_PARAM_MAIN_BOARD_TEMP      = 0x00,//板上
    SERVICE_PARAM_PARAM_MAIN_ENVIR           = 0x01,//环境
    SERVICE_PARAM_PARAM_MAIN_PLATE_REACTION  = 0x02,//反应盘
    SERVICE_PARAM_PARAM_MAIN_PLATE_WASH      = 0x03,//清洗盘
    SERVICE_PARAM_PARAM_MAIN_PLATE_REAGENT   = 0x04,//试剂盘
}SERVICE_PARAM_PARAM_MAIN;

//参数读写子序号,板上
typedef enum SERVICE_PARAM_PARAM_SUB_BOARD_TEMP
{
    SERVICE_PARAM_PARAM_SUB_BOARD_TEMP_MAX_LIMIT = 0X00,//保护温度上
    SERVICE_PARAM_PARAM_SUB_BOARD_TEMP_MIN_LIMIT = 0X01,//保护温度下
}SERVICE_PARAM_PARAM_SUB_BOARD_TEMP;

//参数读写子序号,环境
typedef enum SERVICE_PARAM_PARAM_SUB_ENVIR
{
    SERVICE_PARAM_PARAM_SUB_ENVIR_MAX_LIMIT     = 0X00,//保护温度上
    SERVICE_PARAM_PARAM_SUB_ENVIR_MIN_LIMIT     = 0X01,//保护温度下
    SERVICE_PARAM_PARAM_SUB_ENVIR_TEMP_OPEN_FAN = 0X02,//风扇打开温度
}SERVICE_PARAM_PARAM_SUB_ENVIR;

//参数读写子序号,反应盘
typedef enum SERVICE_PARAM_PARAM_SUB_PLATE_REACTION
{
    SERVICE_PARAM_PARAM_SUB_PLATE_REACTION_TARGET_TEMP       = 0X00,//目标温度
    SERVICE_PARAM_PARAM_SUB_PLATE_REACTION_KP                = 0X01,//比例系数
    SERVICE_PARAM_PARAM_SUB_PLATE_REACTION_KI                = 0X02,//积分系数
    SERVICE_PARAM_PARAM_SUB_PLATE_REACTION_KD                = 0X03,//微分系数
    SERVICE_PARAM_PARAM_SUB_PLATE_REACTION_HIGH_THRESHOLD    = 0X04,//全速降温上阈值
    SERVICE_PARAM_PARAM_SUB_PLATE_REACTION_LOW_THRESHOLD     = 0X05,//全速升温下阈值
    SERVICE_PARAM_PARAM_SUB_PLATE_REACTION_MAX_POWER         = 0X06,//最大输出功率
    SERVICE_PARAM_PARAM_SUB_PLATE_REACTION_MIN_POWER         = 0X07,//最小输出功率
    SERVICE_PARAM_PARAM_SUB_PLATE_REACTION_HIGH_PROTECT      = 0X08,//保护温度上
    SERVICE_PARAM_PARAM_SUB_PLATE_REACTION_LOW_PROTECT       = 0X09,//保护温度下
    SERVICE_PARAM_PARAM_SUB_PLATE_REACTION_KI_TIME_SECOND    = 0X0A,//积分时间,秒
    SERVICE_PARAM_PARAM_SUB_PLATE_REACTION_KD_TIME_SECOND    = 0X0B,//微分时间,秒
}SERVICE_PARAM_PARAM_SUB_PLATE_REACTION;

//参数读写子序号,清洗盘
typedef enum SERVICE_PARAM_PARAM_SUB_PLATE_WASH
{
    SERVICE_PARAM_PARAM_SUB_PLATE_WASH_TARGET_TEMP     = 0X00,//目标温度
    SERVICE_PARAM_PARAM_SUB_PLATE_WASH_KP              = 0X01,//比例系数
    SERVICE_PARAM_PARAM_SUB_PLATE_WASH_KI              = 0X02,//积分系数
    SERVICE_PARAM_PARAM_SUB_PLATE_WASH_KD              = 0X03,//微分系数
    SERVICE_PARAM_PARAM_SUB_PLATE_WASH_HIGH_THRESHOLD  = 0X04,//全速降温上阈值
    SERVICE_PARAM_PARAM_SUB_PLATE_WASH_LOW_THRESHOLD   = 0X05,//全速升温下阈值
    SERVICE_PARAM_PARAM_SUB_PLATE_WASH_MAX_POWER       = 0X06,//最大输出功率
    SERVICE_PARAM_PARAM_SUB_PLATE_WASH_MIN_POWER       = 0X07,//最小输出功率
    SERVICE_PARAM_PARAM_SUB_PLATE_WASH_HIGH_PROTECT    = 0X08,//保护温度上
    SERVICE_PARAM_PARAM_SUB_PLATE_WASH_LOW_PROTECT     = 0X09,//保护温度下
    SERVICE_PARAM_PARAM_SUB_PLATE_WASH_KI_TIME_SECOND  = 0X0A,//积分时间,秒
    SERVICE_PARAM_PARAM_SUB_PLATE_WASH_KD_TIME_SECOND  = 0X0B,//微分时间,秒
}SERVICE_PARAM_PARAM_SUB_PLATE_WASH;

//参数读写子序号,试剂盘
typedef enum SERVICE_PARAM_PARAM_SUB_PLATE_REAGENT
{
    SERVICE_PARAM_PARAM_SUB_PLATE_REAGENT_TARGET_TEMP    = 0X00,//目标温度
    SERVICE_PARAM_PARAM_SUB_PLATE_REAGENT_MAX_POWER      = 0X01,//最大输出功率
    SERVICE_PARAM_PARAM_SUB_PLATE_REAGENT_MIN_POWER      = 0X02,//最小输出功率
    SERVICE_PARAM_PARAM_SUB_PLATE_REAGENT_HIGH_PROTECT   = 0X03,//保护温度上
    SERVICE_PARAM_PARAM_SUB_PLATE_REAGENT_LOW_PROTECT    = 0X04,//保护温度下
    SERVICE_PARAM_PARAM_SUB_PLATE_REAGENT_TEMP_CTRL_TYPE = 0x05,//试剂盘温度控制类型
}SERVICE_PARAM_PARAM_SUB_PLATE_REAGENT;


#endif


