#include "BoardConfigInc.h"
//配置主板输出IO初始化的电平
#include "BoardInOut.h"

//主板输入初始化
//配置输入上拉还是下拉
const GPIOPuPd_TypeDef boardInInitPullConfigArray[BOARD_IN_PIN_COUNT] = {
    GPIO_PuPd_DOWN,//BOARD_IN_CPLD_NOP1
    GPIO_PuPd_DOWN,//BOARD_IN_CPLD_NOP2
    GPIO_PuPd_DOWN,//BOARD_IN_CPLD_NOP3
    GPIO_PuPd_DOWN,//BOARD_IN_CPLD_NOP4
    GPIO_PuPd_DOWN,//BOARD_IN_CPLD_NOP5
    GPIO_PuPd_DOWN,//BOARD_IN_CPLD_NOP6
    GPIO_PuPd_DOWN,//BOARD_IN_CPLD_NOP7
    GPIO_PuPd_DOWN,//BOARD_IN_CPLD_NOP8
    GPIO_PuPd_DOWN,//BOARD_IN_CPLD_NOP9
    GPIO_PuPd_DOWN,//BOARD_IN_CPLD_NOP10
    GPIO_PuPd_DOWN,//BOARD_IN_CPLD_NOP11
    GPIO_PuPd_DOWN,//BOARD_IN_CPLD_NOP12
    GPIO_PuPd_DOWN,//BOARD_IN_CPLD_NOP13
    GPIO_PuPd_DOWN,//BOARD_IN_MCU_ARM_SEN1_PI10
    GPIO_PuPd_DOWN,//BOARD_IN_MCU_ARM_SEN2_PI9
    GPIO_PuPd_DOWN,//BOARD_IN_MCU_ARM_SEN3_PC13
    GPIO_PuPd_DOWN,//BOARD_IN_MCU_ARM_SEN4_PI8
    GPIO_PuPd_DOWN,//BOARD_IN_MCU_ARM_SEN5_PE6
    GPIO_PuPd_DOWN,//BOARD_IN_MCU_ARM_SEN6_PE5
    GPIO_PuPd_DOWN,//BOARD_IN_MCU_ARM_SEN7_PE4
    GPIO_PuPd_DOWN,//BOARD_IN_MCU_ARM_SEN8_PE3
    GPIO_PuPd_DOWN,//BOARD_IN_MCU_ARM_SEN9_PE2
    GPIO_PuPd_DOWN,//BOARD_IN_MCU_ARM_SEN10_PI7
    GPIO_PuPd_DOWN,//BOARD_IN_MCU_ARM_SEN11_PI6
    GPIO_PuPd_DOWN,//BOARD_IN_MCU_ARM_SEN12_PI5
    GPIO_PuPd_DOWN,//BOARD_IN_MCU_ARM_SEN13_PI4
    GPIO_PuPd_DOWN,//BOARD_IN_MCU_ARM_SEN14_PB9
    GPIO_PuPd_DOWN,//BOARD_IN_MCU_ARM_SEN15_PB8
    GPIO_PuPd_DOWN,//BOARD_IN_MCU_ARM_SEN16_PB7
    GPIO_PuPd_DOWN,//BOARD_IN_MCU_SLAVE_ARM_SEN1_PH12
    GPIO_PuPd_DOWN,//BOARD_IN_MCU_SLAVE_ARM_SEN2_PH11
    GPIO_PuPd_DOWN,//BOARD_IN_MCU_SLAVE_ARM_SEN3_PH10
    GPIO_PuPd_DOWN,//BOARD_IN_MCU_SLAVE_ARM_SEN4_PH9
    GPIO_PuPd_DOWN,//BOARD_IN_MCU_SLAVE_ARM_SEN5_PH8
    GPIO_PuPd_DOWN,//BOARD_IN_MCU_SLAVE_ARM_SEN6_PH7
    GPIO_PuPd_DOWN,//BOARD_IN_MCU_SLAVE_ARM_SEN7_PH6
    GPIO_PuPd_DOWN,//BOARD_IN_MCU_SLAVE_ARM_SEN8_PB11
    GPIO_PuPd_DOWN,//BOARD_IN_MCU_SLAVE_ARM_SEN9_PB10
    GPIO_PuPd_DOWN,//BOARD_IN_MCU_SLAVE_ARM_SEN10_PC0
    GPIO_PuPd_DOWN,//BOARD_IN_MCU_SLAVE_ARM_SEN11_PC1
    GPIO_PuPd_DOWN,//BOARD_IN_MCU_SLAVE_ARM_SEN12_PC2
    GPIO_PuPd_DOWN,//BOARD_IN_MCU_SLAVE_ARM_SEN13_PC3
    GPIO_PuPd_DOWN,//BOARD_IN_MCU_SLAVE_ARM_SEN14_PB1
    GPIO_PuPd_DOWN,//BOARD_IN_MCU_SLAVE_ARM_SEN15_PB0
    GPIO_PuPd_DOWN,//BOARD_IN_MCU_SLAVE_ARM_SEN16_PC5
    GPIO_PuPd_DOWN,//BOARD_IN_MCU_FRUBBISH1_PH15
    GPIO_PuPd_DOWN,//BOARD_IN_MCU_FRUBBISH2_PH14
    GPIO_PuPd_DOWN,//BOARD_IN_MCU_FRUBBISH3_PH13
    GPIO_PuPd_DOWN,//BOARD_IN_MCU_FRUBBISH4_PC9
    GPIO_PuPd_DOWN,//BOARD_IN_MCU_FRUBBISH_OVER1_PI0
    GPIO_PuPd_DOWN,//BOARD_IN_MCU_FRUBBISH_OVER2_PI1
    GPIO_PuPd_DOWN,//BOARD_IN_MCU_PR1_ARM1_PG14
    GPIO_PuPd_DOWN,//BOARD_IN_MCU_PR1_ARM2_PG13
    GPIO_PuPd_DOWN,//BOARD_IN_MCU_PR2_ARM1_PG11
    GPIO_PuPd_DOWN,//BOARD_IN_MCU_PR2_ARM2_PG10
    GPIO_PuPd_DOWN,//BOARD_IN_MCU_YM1_ARM1_PB6
    GPIO_PuPd_DOWN,//BOARD_IN_MCU_YM1_ARM2_PB5
};

















