/*******************************************************************
 *Description: Copyright(c) 2018-2025 LiHeBio,All rights reserved.
 *Author: DengXiaoJun
 *Date: 2020-02-19 14:49:50
 *LastEditors: DengXiaoJun
 *LastEditTime: 2020-02-23 16:29:32
 *FilePath: \Appc:\LiHe\Local\02-Development\Software\H360_STM32\LH_RAIL_V2.3\Code\CommonFunc\SystemUtil\SystemOutputIndex.h
 *ModifyRecord1:    
 *ModifyRecord2:    
 *ModifyRecord3:    
 *ModifyRecord4:    
 *ModifyRecord5:    
******************************************************************/
#ifndef __SYSTEM_OUTPUT_INDEX_H_
#define __SYSTEM_OUTPUT_INDEX_H_

typedef enum SYSTEM_OUTPUT_INDEX
{
    SYSTEM_OUTPUT_ACTION_BOARD8_CPLD_CDC1,
    SYSTEM_OUTPUT_ACTION_BOARD8_CPLD_CDC2,
    SYSTEM_OUTPUT_ACTION_BOARD8_CPLD_CDC3,
    SYSTEM_OUTPUT_ACTION_BOARD8_CPLD_CDC4,
    SYSTEM_OUTPUT_ACTION_BOARD8_CPLD_CDC5,
    SYSTEM_OUTPUT_ACTION_BOARD8_CPLD_CDC6,
    SYSTEM_OUTPUT_ACTION_BOARD8_CPLD_CDC7,
    SYSTEM_OUTPUT_ACTION_BOARD8_CPLD_CDC8,
    SYSTEM_OUTPUT_ACTION_BOARD8_CPLD_CDC9,
    SYSTEM_OUTPUT_ACTION_BOARD8_CPLD_CDC10,
    SYSTEM_OUTPUT_ACTION_BOARD8_CPLD_CDC11,
    SYSTEM_OUTPUT_ACTION_BOARD8_CPLD_CDC12,
    SYSTEM_OUTPUT_ACTION_BOARD8_CPLD_CDC13,
    SYSTEM_OUTPUT_ACTION_BOARD8_CPLD_CDC14,
    SYSTEM_OUTPUT_ACTION_BOARD8_CPLD_CDC15,
    SYSTEM_OUTPUT_ACTION_BOARD8_CPLD_CDC16,
    SYSTEM_OUTPUT_ACTION_BOARD8_CPLD_CDC17,
    SYSTEM_OUTPUT_ACTION_BOARD8_CPLD_CDC18,
    SYSTEM_OUTPUT_ACTION_BOARD8_CPLD_CDC19,
    SYSTEM_OUTPUT_ACTION_BOARD8_CPLD_CDC20,
    SYSTEM_OUTPUT_ACTION_BOARD8_CPLD_CDC21,
    SYSTEM_OUTPUT_ACTION_BOARD8_CPLD_CDC22,
    SYSTEM_OUTPUT_ACTION_BOARD8_CPLD_CDC23,
    SYSTEM_OUTPUT_ACTION_BOARD8_CPLD_CDC24,
    SYSTEM_OUTPUT_ACTION_BOARD8_CPLD_CDC25,
    SYSTEM_OUTPUT_ACTION_BOARD8_CPLD_CDC26,
    SYSTEM_OUTPUT_ACTION_BOARD8_CPLD_CDC27,
    SYSTEM_OUTPUT_ACTION_BOARD8_CPLD_CDC28,
    SYSTEM_OUTPUT_ACTION_BOARD8_CPLD_CDC29,
    SYSTEM_OUTPUT_ACTION_BOARD8_CPLD_CDC30,
    SYSTEM_OUTPUT_ACTION_BOARD8_CPLD_CDC31,
    SYSTEM_OUTPUT_ACTION_BOARD8_CPLD_CDC32,
    SYSTEM_OUTPUT_ACTION_BOARD8_CPLD_CDC33,
    SYSTEM_OUTPUT_ACTION_BOARD8_CPLD_CDC34,
    SYSTEM_OUTPUT_ACTION_BOARD8_CPLD_CDC35,
    SYSTEM_OUTPUT_ACTION_BOARD8_CPLD_CDC36,
    SYSTEM_OUTPUT_ACTION_BOARD8_MCU_SLAVE_SEN17_PC4,
    SYSTEM_OUTPUT_ACTION_BOARD8_MCU_SLAVE_SEN18_PA7,
    SYSTEM_OUTPUT_ACTION_BOARD8_MCU_SLAVE_SEN19_PA6,
    SYSTEM_OUTPUT_ACTION_BOARD8_MCU_SLAVE_SEN20_PA5,
    SYSTEM_OUTPUT_ACTION_BOARD8_MCU_SLAVE_SEN21_PA4,
    SYSTEM_OUTPUT_ACTION_BOARD8_MCU_SLAVE_SEN22_PA3,
    SYSTEM_OUTPUT_ACTION_BOARD8_MCU_SLAVE_SEN23_PF8,
    SYSTEM_OUTPUT_ACTION_BOARD8_MCU_SLAVE_SEN24_PF9,
    SYSTEM_OUTPUT_ACTION_BOARD8_MCU_SLAVE_SEN25_PF10,
    SYSTEM_OUTPUT_ACTION_BOARD8_MCU_SLAVE_SEN26_PH3,
    SYSTEM_OUTPUT_ACTION_BOARD8_MCU_SLAVE_SEN27_PH2,
    SYSTEM_OUTPUT_ACTION_BOARD8_MCU_SLAVE_SEN28_PA2,
    SYSTEM_OUTPUT_ACTION_BOARD8_MCU_SLAVE_DC1_PC8,
    SYSTEM_OUTPUT_ACTION_BOARD8_MCU_SLAVE_DC2_PG9,
    SYSTEM_OUTPUT_ACTION_BOARD8_MCU_SLAVE_DC3_PD6,
    SYSTEM_OUTPUT_ACTION_BOARD8_MCU_SLAVE_DC4_PI3,
    SYSTEM_OUTPUT_ACTION_BOARD8_MCU_SLAVE_DC5_PI2,
    SYSTEM_OUTPUT_ACTION_BOARD8_MCU_YM_ARM3_PB4,
    SYSTEM_OUTPUT_ACTION_BOARD8_MCU_YM_ARM4_PG15,
    //主控板
    SYSTEM_OUTPUT_RAIL_BOARD_ARM_OUT1_PG15,
    SYSTEM_OUTPUT_RAIL_BOARD_ARM_OUT2_PB3,
    SYSTEM_OUTPUT_RAIL_BOARD_ARM_OUT3_PB4,
    SYSTEM_OUTPUT_RAIL_BOARD_ARM_OUT4_PG14,
    SYSTEM_OUTPUT_RAIL_BOARD_ARM_OUT5_PG13,
    SYSTEM_OUTPUT_RAIL_BOARD_ARM_OUT6_PG11,
    SYSTEM_OUTPUT_RAIL_BOARD_ARM_OUT7_PI3,
    SYSTEM_OUTPUT_RAIL_BOARD_ARM_OUT8_PA15,
    SYSTEM_OUTPUT_RAIL_BOARD_ARM_OUT9_PD6,
    SYSTEM_OUTPUT_RAIL_BOARD_ARM_OUT10_PG10,
    SYSTEM_OUTPUT_RAIL_BOARD_ARM_OUT11_PG9,
    SYSTEM_OUTPUT_RAIL_BOARD_ARM_OUT12_PD7,
    SYSTEM_OUTPUT_RAIL_BOARD_ARM_OUT13_PG8,
    SYSTEM_OUTPUT_RAIL_BOARD_ARM_OUT14_PI1,
    SYSTEM_OUTPUT_RAIL_BOARD_ARM_OUT15_PI0,
    SYSTEM_OUTPUT_RAIL_BOARD_ARM_OUT16_PG6,
    SYSTEM_OUTPUT_RAIL_BOARD_ARM_OUT17_PG7,
    SYSTEM_OUTPUT_RAIL_BOARD_ARM_OUT18_PH12,
    SYSTEM_OUTPUT_RAIL_BOARD_ARM_OUT19_PI2,
    SYSTEM_OUTPUT_RAIL_BOARD_ARM_OUT20_PD3,
}SYSTEM_OUTPUT_INDEX;

#endif




