/*******************************************************************
 *Description: Copyright(c) 2018-2025 LiHeBio,All rights reserved.
 *Author: DengXiaoJun
 *Date: 2020-02-11 13:55:22
 *LastEditors: DengXiaoJun
 *LastEditTime: 2020-07-29 09:21:55
 *FilePath: \H360_ActionBoard_ID_4\TaskMain\AppSupport\AppUtil\AppParamIndex.h
 *ModifyRecord1:    
 *ModifyRecord2:    
 *ModifyRecord3:    
 *ModifyRecord4:    
 *ModifyRecord5:    
******************************************************************/
#ifndef __APP_PARAM_INDEX_H_
#define __APP_PARAM_INDEX_H_
#include "stm32f4xx.h"


//试剂混匀参数子序号,序号从1开始
typedef enum APP_PARAM_SUB_INDEX_MIX_REAGENT
{
    APP_PARAM_SUB_INDEX_MIX_REAGENT_RESET_CORRECT_UPDOWN   = 0X01,//试剂混匀升降零位修正
    APP_PARAM_SUB_INDEX_MIX_REAGENT_RESET_CORRECT_ROTATE   = 0X02,//试剂混匀旋转零位修正
    APP_PARAM_SUB_INDEX_MIX_REAGENT_UP_POS_MODE1           = 0X03,//试剂混匀模式1升降高度
    APP_PARAM_SUB_INDEX_MIX_REAGENT_ROTATE_TIME_MS_MODE1   = 0X04,//试剂混匀模式1摇匀时间,毫秒
    APP_PARAM_SUB_INDEX_MIX_REAGENT_UP_POS_MODE2           = 0X05,//试剂混匀模式2升降高度
    APP_PARAM_SUB_INDEX_MIX_REAGENT_ROTATE_TIME_MS_MODE2   = 0X06,//试剂混匀模式2摇匀时间,毫秒
    APP_PARAM_SUB_INDEX_MIX_REAGENT_UP_POS_MODE3           = 0X07,//试剂混匀模式3升降高度
    APP_PARAM_SUB_INDEX_MIX_REAGENT_ROTATE_TIME_MS_MODE3   = 0X08,//试剂混匀模式3摇匀时间,毫秒
    APP_PARAM_SUB_INDEX_MIX_REAGENT_UP_POS_MODE4           = 0X09,//试剂混匀模式4升降高度
    APP_PARAM_SUB_INDEX_MIX_REAGENT_ROTATE_TIME_MS_MODE4   = 0X0A,//试剂混匀模式4摇匀时间,毫秒
    APP_PARAM_SUB_INDEX_MIX_REAGENT_UP_POS_MODE5           = 0X0B,//试剂混匀模式5升降高度
    APP_PARAM_SUB_INDEX_MIX_REAGENT_ROTATE_TIME_MS_MODE5   = 0X0C,//试剂混匀模式5摇匀时间,毫秒
    APP_PARAM_SUB_INDEX_MIX_REAGENT_UP_POS_MODE6           = 0X0D,//试剂混匀模式6升降高度
    APP_PARAM_SUB_INDEX_MIX_REAGENT_ROTATE_TIME_MS_MODE6   = 0X0E,//试剂混匀模式6摇匀时间,毫秒
    APP_PARAM_SUB_INDEX_MIX_REAGENT_UP_POS_MODE7           = 0X0F,//试剂混匀模式7升降高度
    APP_PARAM_SUB_INDEX_MIX_REAGENT_ROTATE_TIME_MS_MODE7   = 0X10,//试剂混匀模式7摇匀时间,毫秒
    APP_PARAM_SUB_INDEX_MIX_REAGENT_UP_POS_MODE8           = 0X11,//试剂混匀模式8升降高度
    APP_PARAM_SUB_INDEX_MIX_REAGENT_ROTATE_TIME_MS_MODE8   = 0X12,//试剂混匀模式8摇匀时间,毫秒
    APP_PARAM_SUB_INDEX_MIX_REAGENT_UP_POS_MODE9           = 0X13,//试剂混匀模式9升降高度
    APP_PARAM_SUB_INDEX_MIX_REAGENT_ROTATE_TIME_MS_MODE9   = 0X14,//试剂混匀模式9摇匀时间,毫秒
    APP_PARAM_SUB_INDEX_MIX_REAGENT_UP_POS_MODE10          = 0X15,//试剂混匀模式10升降高度
    APP_PARAM_SUB_INDEX_MIX_REAGENT_ROTATE_TIME_MS_MODE10  = 0X16,//试剂混匀模式10摇匀时间,毫秒
    APP_PARAM_SUB_INDEX_MIX_REAGENT_MOTOR_CONFIG_VERSION   = 0X17,//试剂混匀电机配置
}APP_PARAM_SUB_INDEX_MIX_REAGENT;


//试剂针参数子序号,序号从1开始
typedef enum APP_PARAM_SUB_INDEX_NEEDLE_REAGENT
{
    APP_PARAM_SUB_INDEX_NEEDLE_REAGENT_ROTATE_RESET_CORRECT					    = 0X01,//试剂针旋转零位修正
    APP_PARAM_SUB_INDEX_NEEDLE_REAGENT_UPDOWN_RESET_CORRECT					    = 0X02,//试剂针升降零位修正
    APP_PARAM_SUB_INDEX_NEEDLE_REAGENT_POS_ROTATE_TO_CLEAN						= 0X03,//试剂针旋转到清洗位坐标
    APP_PARAM_SUB_INDEX_NEEDLE_REAGENT_POS_UPDOWN_CLEAN						    = 0X04,//试剂针升降到清洗位坐标
    // APP_PARAM_SUB_INDEX_NEEDLE_REAGENT_TIME_MS_CLEAN_SET1						= 0X05,//试剂针清洗时间1,毫秒
    // APP_PARAM_SUB_INDEX_NEEDLE_REAGENT_TIME_MS_CLEAN_SET2						= 0X06,//试剂针清洗时间2,毫秒
    // APP_PARAM_SUB_INDEX_NEEDLE_REAGENT_TIME_MS_CLEAN_SET3						= 0X07,//试剂针清洗时间3,毫秒
    // APP_PARAM_SUB_INDEX_NEEDLE_REAGENT_TIME_MS_CLEAN_SET4						= 0X08,//试剂针清洗时间4,毫秒
    // APP_PARAM_SUB_INDEX_NEEDLE_REAGENT_TIME_MS_CLEAN_SET5						= 0X09,//试剂针清洗时间5,毫秒
    // APP_PARAM_SUB_INDEX_NEEDLE_REAGENT_TIME_MS_PRIME							= 0X0A,//试剂针清洗液灌注时间,毫秒
    APP_PARAM_SUB_INDEX_NEEDLE_REAGENT_POS_ROTATE_TO_R1						    = 0X0B,//试剂针旋转到R1坐标
    // APP_PARAM_SUB_INDEX_NEEDLE_REAGENT_POS_UPDOWN_R1_LIQUID_DETECT_START		= 0X0C,//试剂针升降R1吸样探液起始点
    APP_PARAM_SUB_INDEX_NEEDLE_REAGENT_POS_UPDOWN_R1_LIQUID_DETECT_MAX_LIMIT	= 0X0D,//试剂针升降R1吸样探液极限点
    APP_PARAM_SUB_INDEX_NEEDLE_REAGENT_POS_ROTATE_TO_R2						    = 0X0E,//试剂针旋转到R2坐标
    // APP_PARAM_SUB_INDEX_NEEDLE_REAGENT_POS_UPDOWN_R2_LIQUID_DETECT_START		= 0X0F,//试剂针升降R2吸样探液起始点
    APP_PARAM_SUB_INDEX_NEEDLE_REAGENT_POS_UPDOWN_R2_LIQUID_DETECT_MAX_LIMIT	= 0X10,//试剂针升降R2吸样探液极限点
    APP_PARAM_SUB_INDEX_NEEDLE_REAGENT_POS_ROTATE_TO_PLATE_REACTION			    = 0X11,//试剂针旋转到反应盘排样坐标
    APP_PARAM_SUB_INDEX_NEEDLE_REAGENT_POS_UPDOWN_INJECT_AT_BOTTOM			    = 0X12,//试剂针升降反应盘排样杯底高度
    APP_PARAM_SUB_INDEX_NEEDLE_REAGENT_POS_UPDOWN_INJECT_CORRECT				= 0X13,//试剂针升降反应盘排样修正高度
    // APP_PARAM_SUB_INDEX_NEEDLE_REAGENT_POS_UPDOWN_INJECT3						= 0X14,//试剂针升降反应盘排样高度3
    // APP_PARAM_SUB_INDEX_NEEDLE_REAGENT_POS_UPDOWN_INJECT4						= 0X15,//试剂针升降反应盘排样高度4
    // APP_PARAM_SUB_INDEX_NEEDLE_REAGENT_POS_UPDOWN_INJECT5						= 0X16,//试剂针升降反应盘排样高度5
    // APP_PARAM_SUB_INDEX_NEEDLE_REAGENT_POS_UPDOWN_INJECT6						= 0X17,//试剂针升降反应盘排样高度6
    // APP_PARAM_SUB_INDEX_NEEDLE_REAGENT_POS_UPDOWN_INJECT7						= 0X18,//试剂针升降反应盘排样高度7
    // APP_PARAM_SUB_INDEX_NEEDLE_REAGENT_POS_UPDOWN_INJECT8_DEEPEST				= 0X19,//试剂针升降反应盘排样高度8,最深
    APP_PARAM_SUB_INDEX_NEEDLE_REAGENT_UL_ABSORB_AIR_AFTER_CLEAN				= 0X1A,//试剂针清洗完吸空气量
    APP_PARAM_SUB_INDEX_NEEDLE_REAGENT_UL_ABSORB_AIR_AFTER_LIQUID_ABSORB		= 0X1B,//试剂针吸样完吸空气量
    APP_PARAM_SUB_INDEX_NEEDLE_REAGENT_UL_RESERVE_AIR_AFTER_INJECT				= 0X1C,//试剂针注液保留空气量
    APP_PARAM_SUB_INDEX_NEEDLE_REAGENT_LIQUID_DETECT_REAL_TIME_COMM			    = 0X1D,//试剂针探液通讯使能
    APP_PARAM_SUB_INDEX_NEEDLE_REAGENT_PUMP_GEAR_GAP			                = 0X1E,//试剂针齿间差
    APP_PARAM_SUB_INDEX_NEEDLE_REAGENT_LIQUID_BOARD_VERSION_WB			        = 0X1F,//试剂针探液板版本号回填确认
}APP_PARAM_SUB_INDEX_NEEDLE_REAGENT;

//磁珠混匀参数子序号,序号从1开始
typedef enum APP_PARAM_SUB_INDEX_MIX_BEAD
{
    APP_PARAM_SUB_INDEX_MIX_BEAD_RESET_CORRECT_UPDOWN   = 0X01,//磁珠混匀升降零位修正
    APP_PARAM_SUB_INDEX_MIX_BEAD_RESET_CORRECT_ROTATE   = 0X02,//磁珠混匀旋转零位修正
    APP_PARAM_SUB_INDEX_MIX_BEAD_UP_POS_MODE1           = 0X03,//磁珠混匀模式1升降高度
    APP_PARAM_SUB_INDEX_MIX_BEAD_ROTATE_TIME_MS_MODE1   = 0X04,//磁珠混匀模式1摇匀时间,毫秒
    APP_PARAM_SUB_INDEX_MIX_BEAD_UP_POS_MODE2           = 0X05,//磁珠混匀模式2升降高度
    APP_PARAM_SUB_INDEX_MIX_BEAD_ROTATE_TIME_MS_MODE2   = 0X06,//磁珠混匀模式2摇匀时间,毫秒
    APP_PARAM_SUB_INDEX_MIX_BEAD_UP_POS_MODE3           = 0X07,//磁珠混匀模式3升降高度
    APP_PARAM_SUB_INDEX_MIX_BEAD_ROTATE_TIME_MS_MODE3   = 0X08,//磁珠混匀模式3摇匀时间,毫秒
    APP_PARAM_SUB_INDEX_MIX_BEAD_UP_POS_MODE4           = 0X09,//磁珠混匀模式4升降高度
    APP_PARAM_SUB_INDEX_MIX_BEAD_ROTATE_TIME_MS_MODE4   = 0X0A,//磁珠混匀模式4摇匀时间,毫秒
    APP_PARAM_SUB_INDEX_MIX_BEAD_UP_POS_MODE5           = 0X0B,//磁珠混匀模式5升降高度
    APP_PARAM_SUB_INDEX_MIX_BEAD_ROTATE_TIME_MS_MODE5   = 0X0C,//磁珠混匀模式5摇匀时间,毫秒
    APP_PARAM_SUB_INDEX_MIX_BEAD_UP_POS_MODE6           = 0X0D,//磁珠混匀模式6升降高度
    APP_PARAM_SUB_INDEX_MIX_BEAD_ROTATE_TIME_MS_MODE6   = 0X0E,//磁珠混匀模式6摇匀时间,毫秒
    APP_PARAM_SUB_INDEX_MIX_BEAD_UP_POS_MODE7           = 0X0F,//磁珠混匀模式7升降高度
    APP_PARAM_SUB_INDEX_MIX_BEAD_ROTATE_TIME_MS_MODE7   = 0X10,//磁珠混匀模式7摇匀时间,毫秒
    APP_PARAM_SUB_INDEX_MIX_BEAD_UP_POS_MODE8           = 0X11,//磁珠混匀模式8升降高度
    APP_PARAM_SUB_INDEX_MIX_BEAD_ROTATE_TIME_MS_MODE8   = 0X12,//磁珠混匀模式8摇匀时间,毫秒
    APP_PARAM_SUB_INDEX_MIX_BEAD_UP_POS_MODE9           = 0X13,//磁珠混匀模式9升降高度
    APP_PARAM_SUB_INDEX_MIX_BEAD_ROTATE_TIME_MS_MODE9   = 0X14,//磁珠混匀模式9摇匀时间,毫秒
    APP_PARAM_SUB_INDEX_MIX_BEAD_UP_POS_MODE10          = 0X15,//磁珠混匀模式10升降高度
    APP_PARAM_SUB_INDEX_MIX_BEAD_ROTATE_TIME_MS_MODE10  = 0X16,//磁珠混匀模式10摇匀时间,毫秒
    APP_PARAM_SUB_INDEX_MIX_BEAD_MOTOR_CONFIG_VERSION   = 0X17,//磁珠混匀电机配置
}APP_PARAM_SUB_INDEX_MIX_BEAD;


//反应盘
typedef enum APP_PARAM_SUB_INDEX_PLATE_REACTION
{
    APP_PARAM_SUB_INDEX_PLATE_REACTION_ROTATE_RESET_CORRECT = 0X01,//旋转零位修正
}APP_PARAM_SUB_INDEX_PLATE_REACTION;

//其余支持
typedef enum APP_PARAM_SUB_INDEX_OTHER
{
    APP_PARAM_SUB_INDEX_OTHER_UTIL = 0X01,//辅助参数
}APP_PARAM_SUB_INDEX_OTHER;


#endif
