#ifndef __BOARD_COMM_BASE_H_
#define __BOARD_COMM_BASE_H_
#include "MCU_Inc.h"

//IO信号状态
typedef enum IO_SIGNAL_STATE
{   
    IO_SIGNAL_INVALID = 0,//io量无效
    IO_SIGNAL_VALID   = 1,//io量有效
}IO_SIGNAL_STATE;

//热电偶芯片通道
typedef enum CHANNEL_MAX31856
{
    CHANNEL_MAX31856_PLATE_REAGENT  = 0,
    CHANNEL_MAX31856_PLATE_REACTION = 1,
    CHANNEL_MAX31856_PLATE_WASH     = 2,
    CHANNEL_MAX31856_ENVIRMENT      = 3,
}CHANNEL_MAX31856;

//电流检测通道
typedef enum CHANNEL_CURRENT_DETECT
{
    PLATE_REAGENT_1_CURRENT_DETECT = 0,
    PLATE_REAGENT_2_CURRENT_DETECT = 1,
    PLATE_REAGENT_3_CURRENT_DETECT = 2,
    PLATE_REAGENT_4_CURRENT_DETECT = 3,
    PLATE_REACTION_CURRENT_DETECT  = 4,
    PLATE_WASH_CURRENT_DETECT      = 5,
    PLATE_REAGENT_COOLER_CURRENT_DETECT = 6,
}CHANNEL_CURRENT_DETECT;


#endif




